title: Elektroniklådan
company: Elektroniklådan i Bro AB
description: Utveckling och utbildning inom elektronik och firmware.
org_info: >-
  org.nr: 559262-8670
address: >-
  Bergsmansvägen 6
  812 90 Storvik
#email: your-email@example.com
logo: assets/img/logo-v1.png
lang: sv
#github_username:  elektronikladan
#linkedin_username: elektronikladan

url: "https://elektronikladan.se"
baseurl: ""

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-seo-tag
